# Generated by Django 5.2.8 on 2025-11-19 15:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('github_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('summary', models.TextField(blank=True, max_length=800, null=True)),
                ('blog_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('content', models.TextField()),
                ('author', models.CharField(default='Ax de Klerk', max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_image_page_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cv_image_page_1')),
                ('cv_image_page_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cv_image_page_2')),
                ('pdf_cv_link', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('doc_cv_link', models.FileField(blank=True, null=True, upload_to='cv/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('description', models.TextField()),
                ('tools_used', models.CharField(blank=True, max_length=300, null=True)),
                ('grade_received', models.CharField(blank=True, max_length=50, null=True)),
                ('deployed_project_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('submission_date', models.DateTimeField()),
            ],
        ),
    ]
